#include <fstream.h>
//#include <process.h>

int n;

void main()
{ int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0,x=0,y=0,z=0,max;

  char a1,b1;
  while(!fin.fail())
    { cin >> a1;
      if(a1=='a')
	a++;
      if(a1=='b')
	b++;
      if(a1=='c')
	c++;
      if(a1=='d')
	d++;
      if(a1=='e')
	e++;
      if(a1=='f')
	f++;
      if(a1=='g')
	g++;
      if(a1=='h')
	h++;
      if(a1=='i')
	i++;
      if(a1=='j')
	j++;
      if(a1=='k')
	k++;
      if(a1=='l')
	l++;
      if(a1=='m')
	m++;
      if(a1=='n')
	n++;
      if(a1=='o')
	o++;
      if(a1=='p')
	p++;
      if(a1=='q')
	q++;
      if(a1=='r')
	r++;
      if(a1=='s')
	s++;
      if(a1=='t')
	t++;
      if(a1=='u')
	u++;
      if(a1=='v')
	v++;
      if(a1=='w')
	w++;
      if(a1=='x')
	x++;
      if(a1=='y')
	y++;
      if(a1=='z')
	z++;
    }
  cout << a;
  cout << endl;
  cout  << endl;
 if(a>b && a>c && a>d && a>e && a>f && a>g && a>h && a>i && a>j && a>k && a>l && a>m && a>n && a>o && a>p && a>q && a>r && a>s && a>t && a>u && a>v && a>w && a>x && a>y && a>z )
   { //cout << "a" << a;
     max=a;
     b1='a';
     // exit;
    }
 if(b>max )
   {// cout << "b" << b;
//     exit;
     max=b;
     b1='b';
   }
  if(c>max )
   {// cout << "c" << c;
//     exit;
    max=c;
    b1='c';
   }
 if(d>max)
   {// cout << "d" << d;
 //    exit;
    max=d;
     b1='d';

   }
  if(e>max)
   { //cout << "e" << e;
//     exit;
   max=e;
     b1='e';

   }
  if(f>max)
   { //cout << "f" << f;
//    exit;
 max=f;
     b1='f';

   }
   if(g>max)
      { //cout << "g" << g;
//     exit;
  max=g;
     b1='g';

   }
  if(h>max)
   { //cout << "h" << h;
   max=h;
     b1='h';

  //   exit;
   }
  if(i>max)
   { //cout << "i" << i;
    max=i;
     b1='i';

  //   exit;
   }
  if(j>max)
   { //cout << "j" << b;
    max=j;
     b1='j';

//     exit;
   }
  if(k>max)
   { //cout << "k" << k;
    max=k;
     b1='k';

//     exit;
   }
  if(l>max)
   { //cout << "l" << l;
    max=l;
     b1='l';

//     exit;
   }
  if(m>max)
   { //cout << "m" << m;
//     exit;
 max=m;
     b1='m';

   }
   if(n>max)
   { //cout << "n" << n;
     max=n;
     b1='n';

//     exit;
   }
   if(o>max)
   { //cout << "o" << o;
    max=o;
     b1='o';

//     exit;
   }
  if(p>max)
   { //cout << "p" << p;
    max=p;
     b1='p';

//     exit;
   }

   if(q>max)
   { //cout << "q" << q;
    max=q;
     b1='q';

//     exit;
   }
   if(r>max)
   { //cout << "r" << r;
    max=r;
     b1='r';

 //    exit;
   }
   if(s>max)
   { //cout << "s" << s;
    max=s;
     b1='s';

  //   exit;
   }
   if(t>max)
   { //cout << "t" << t;
    max=t;
     b1='t';

 //    exit;
   }
   if(u>max)
   { //cout << "u" << u;
    max=u;
     b1='u';

  //   exit;
   }
   if(v>max)
   { //cout << "v" << v;
    max=v;
     b1='v';

   //  exit;
   }
  if(w>max)
   { //cout << "w" << w;
    max=w;
     b1='w';

    // exit;
   }
   if(x>max)
   { //cout << "x" << x;
     max=x;
     b1='x';

   }
   if(y>max)
   { //cout << "y" << y;
       max=y;
     b1='y';

   }
  // else if (z>1) cout << "z" << z;
  if(z>max)
    { max=z;
      b1='y';
    }
  cout << b1 << z;


}