


if %1 == 0 goto 0
if %1 == 1 goto 1
if %1 == 2 goto 2
if %1 == 3 goto 3
if %1 == 4 goto 4
if %1 == 5 goto 5
if %1 == 6 goto 6
if %1 == 7 goto 7
if %1 == 8 goto 8
if %1 == 9 goto 9

:0
call do 0
pause
:1
call do 1
pause
:2
call do 2
pause
:3
call do 3
pause
:4
call do 4
pause
:5
call do 5
pause
:6
call do 6
pause
:7
call do 7
pause
:8
call do 8
pause
:9
call do 9
pause
