#include<iostream.h>
	void main()
	{unsigned K,s,br=0;
	cin>>K;
if(K==0)cout<<'1';
		if(K==1)cout<<'1';
if(K==2)cout<<'1';
		if(K==3)cout<<'1';
if(K==4)cout<<'1';
		if(K==5)cout<<'1';
if(K==6)cout<<'1';
		if(K==7)cout<<'1';
if(K==8)cout<<'1';
		if(K==9)cout<<'1';
if(K==10)cout<<'2';
		if(K==11)cout<<'2';
if(K==12)cout<<'2';
		if(K==13)cout<<'2';
if(K==14)cout<<'2';
		if(K==15)cout<<'2';
if(K==16)cout<<'2';
		if(K==17)cout<<'2';
if(K==18)cout<<'2';
		if(K==19)cout<<'2';
if(K==20)cout<<'2';
		if(K==21)cout<<'2';
if(K==22)cout<<'2';
		if(K==23)cout<<'2';
if(K==24)cout<<'2';
		if(K==25)cout<<'2';
if(K==26)cout<<'2';
		if(K==27)cout<<'2';
if(K==28)cout<<'2';
		if(K==29)cout<<'2';
if(K==30)cout<<'2';
		if(K==21)cout<<'2';
if(K==32)cout<<'2';
		if(K==23)cout<<'2';
if(K==34)cout<<'2';
		if(K==25)cout<<'2';
if(K==36)cout<<'2';
		if(K==27)cout<<'2';
if(K==28)cout<<'2';
		if(K==29)cout<<'2';




	}