#include<iostream>
using namespace std;
int main()
{
    int a,l=0,b=0,c=0,q=0,w=0,e=0,d=0,f=0,g=0,r=0,o=0,t=0,z=0;
    char n;
    cin>>a;
    do
    {
        cin.get(n);
        if(n=='C')
        {
            if(b==0)
            {
                b=1;
                g++;
            }
        }
        if(n=='A')
        {
            if(c==0)
            {
                c=1;
                g++;
            }
        }
        if(n=='T')
        {
            if(d==0)
            {
                d=3;
                g++;
            }
        }
        if(n=='G')
        {
            if(q==0)
            {
                q=1;
                f++;
            }
        }
        if(n=='P')
        {
            if(w==0)
            {
                w=2;
                f++;
            }
        }
        if(n=='I')
        {
            if(e==0)
            {
                e=3;
                f++;
            }
        }
        if(n=='\n')
        {
            l++;
            g=0;
            f=0;
            if(g>f)
            {
               cout<<"CAT\n";
            }
            if(g<f)
            {
               cout<<"CAT-GPI\n";
            }
            if(f==g)
            {
                cout<<"CAT-GPI\n";
            }
            if(g==0&&f==0)
            {
                cout<<"UFO\n";
            }
        }
    }
    while(l<=a);
    do
    {
        
        if(t!=0)
        {
            cout<<"CAT-GPI\n";
            t--;
        }
        if(z!=0)
        {
            cout<<"UFO\n";
            z--;
        }
        if(r!=0)
        {
            cout<<"CAT\n";
            r--;
        }
        if(o!=0)
        {
            cout<<"CAT-GPI\n";
            o--;
        }
    }
    while(r!=0&&o!=0&&t!=0&&z!=0);
    return 0;
}
