#include<bits/stdc++.h>
using namespace std;
int n;
int used2[1000],used3[1000],used[1000];
void ff(int x){
   memset(used2,0,sizeof(used2));
   if(x==1){
      used2[3]++;
      used2[6]++;
   }
   if(x==2){
      used2[1]++;
      used2[3]++;
      used2[4]++;
      used2[5]++;
      used2[7]++;
   }
   if(x==3){
      used2[1]++;
      used2[3]++;
      used2[4]++;
      used2[6]++;
      used2[7]++;
   }
   if(x==4){
      used2[2]++;
      used2[3]++;
      used2[4]++;
      used2[6]++;
   }
   if(x==5){
      used2[1]++;
      used2[2]++;
      used2[4]++;
      used2[6]++;
      used2[7]++;
   }
   if(x==6){
      used2[1]++;
      used2[2]++;
      used2[4]++;
      used2[5]++;
      used2[6]++;
      used2[7]++;
   }
   if(x==7){
      used2[1]++;
      used2[3]++;
      used2[6]++;
   }
   if(x==8){
      used2[1]++;
      used2[2]++;
      used2[3]++;
      used2[4]++;
      used2[5]++;
      used2[6]++;
      used2[7]++;
   }
   if(x==9){
      used2[1]++;
      used2[2]++;
      used2[3]++;
      used2[4]++;
      used2[6]++;
      used2[7]++;
   }
   if(x==0){
      used2[1]++;
      used2[2]++;
      used2[3]++;
      used2[5]++;
      used2[6]++;
      used2[7]++;
   }
}
void ff2(int x){
   memset(used3,0,sizeof(used3));
   if(x==1){
      used3[3]++;
      used3[6]++;
   }
   if(x==2){
      used3[1]++;
      used3[3]++;
      used3[4]++;
      used3[5]++;
      used3[7]++;
   }
   if(x==3){
      used3[1]++;
      used3[3]++;
      used3[4]++;
      used3[6]++;
      used3[7]++;
   }
   if(x==4){
      used3[2]++;
      used3[3]++;
      used3[4]++;
      used3[6]++;
   }
   if(x==5){
      used3[1]++;
      used3[2]++;
      used3[4]++;
      used3[6]++;
      used3[7]++;
   }
   if(x==6){
      used3[1]++;
      used3[2]++;
      used3[4]++;
      used3[5]++;
      used3[6]++;
      used3[7]++;
   }
   if(x==7){
      used3[1]++;
      used3[3]++;
      used3[6]++;
   }
   if(x==8){
      used3[1]++;
      used3[2]++;
      used3[3]++;
      used3[4]++;
      used3[5]++;
      used3[6]++;
      used3[7]++;
   }
   if(x==9){
      used3[1]++;
      used3[2]++;
      used3[3]++;
      used3[4]++;
      used3[6]++;
      used3[7]++;
   }
   if(x==0){
      used3[1]++;
      used3[2]++;
      used3[3]++;
      used3[5]++;
      used3[6]++;
      used3[7]++;
   }
}
void ff3(int x){
   memset(used,0,sizeof(used));
   if(x==1){
      used[3]++;
      used[6]++;
   }
   if(x==2){
      used[1]++;
      used[3]++;
      used[4]++;
      used[5]++;
      used[7]++;
   }
   if(x==3){
      used[1]++;
      used[3]++;
      used[4]++;
      used[6]++;
      used[7]++;
   }
   if(x==4){
      used[2]++;
      used[3]++;
      used[4]++;
      used[6]++;
   }
   if(x==5){
      used[1]++;
      used[2]++;
      used[4]++;
      used[6]++;
      used[7]++;
   }
   if(x==6){
      used[1]++;
      used[2]++;
      used[4]++;
      used[5]++;
      used[6]++;
      used[7]++;
   }
   if(x==7){
      used[1]++;
      used[3]++;
      used[6]++;
   }
   if(x==8){
      used[1]++;
      used[2]++;
      used[3]++;
      used[4]++;
      used[5]++;
      used[6]++;
      used[7]++;
   }
   if(x==9){
      used[1]++;
      used[2]++;
      used[3]++;
      used[4]++;
      used[6]++;
      used[7]++;
   }
   if(x==0){
      used[1]++;
      used[2]++;
      used[3]++;
      used[5]++;
      used[6]++;
      used[7]++;
   }
}
int main(){
   cin>>n;
   ff(n/10);
   ff2(n%10);
   int br=0;
   for(int i=0;i<=99;i++){
      ff3(i/10);
      int fl=1;
      for(int j=0;j<10;j++){
         if(used[j]==0&&used2[j]==1)fl=0;
      }
      ff3(i%10);
      for(int j=0;j<10;j++){
         if(used[j]==0&&used3[j]==1)fl=0;
      }
      if(fl)br++;
   }
   cout<<br<<"\n";
}
